#include "c99.h"

#include "ctu/util/str.h"

#include "type.h"

typedef struct {
    reports_t *reports;
    module_t *mod;

    stream_t *result;
} context_t;

static context_t *init_c99_context(reports_t *reports, module_t *mod) {
    context_t *ctx = NEW(context_t);
    ctx->reports = reports;
    ctx->mod = mod;
    ctx->result = stream_new(0x1000);
    return ctx;
}

static void forward_global(context_t *ctx, const block_t *block) {
    const type_t *type = block->type;
    const char *name = block->name;

    const char *decl = type_to_string(type, name);

    char *forward = format("%s;\n", decl);

    stream_write(ctx->result, forward);
}

static void add_global(context_t *ctx, const block_t *block) {
    const type_t *type = block->type;
    const value_t *value = block->value;
    const char *name = block->name;

    const char *start = type_to_string(type, name);
    const char *init = value_to_string(value);

    char *fmt = format("%s = %s;\n", start, init);

    stream_write(ctx->result, fmt);
}

static void add_globals(context_t *ctx, vector_t *globals) {
    size_t len = vector_len(globals);
    
    stream_write(ctx->result, "\n// Global forwarding\n");
    
    for (size_t i = 0; i < len; i++) {
        const block_t *block = vector_get(globals, i);
        forward_global(ctx, block);
    }

    stream_write(ctx->result, "\n// Global initialization\n");

    for (size_t i = 0; i < len; i++) {
        const block_t *block = vector_get(globals, i);
        add_global(ctx, block);
    }
}

static void forward_block(context_t *ctx, const block_t *block) {
    (void) ctx;
    (void) block;
}

static void add_block(context_t *ctx, const block_t *block) {
    (void) ctx;
    (void) block;
}

static void add_blocks(context_t *ctx, vector_t *blocks) {
    size_t len = vector_len(blocks);

    stream_write(ctx->result, "\n// Function forwarding\n");

    for (size_t i = 0; i < len; i++) {
        const block_t *block = vector_get(blocks, i);
        forward_block(ctx, block);
    }

    stream_write(ctx->result, "\n// Function definitions\n");

    for (size_t i = 0; i < len; i++) {
        const block_t *block = vector_get(blocks, i);
        add_block(ctx, block);
    }
}

bool c99_build(reports_t *reports, module_t *mod, const char *path) {
    context_t *ctx = init_c99_context(reports, mod);
    
    char *header = format(
        "/**\n"
        " * Autogenerated by %s\n"
        " */\n",
        path
    );

    stream_write(ctx->result, header);

    add_globals(ctx, mod->vars);

    add_blocks(ctx, mod->funcs);

    printf("%s\n", stream_data(ctx->result));

    assert2(reports, "c99 unimplemented %p %s", mod, path);
    return false;
}
