/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from mnt::c::Users::ehb56::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>
#include <stdlib.h>

// String literals
// Imported symbols

// Global forwarding
signed int x[3];

// Function forwarding

// Global initialization
signed int signed int x[3][3] = { {pÔ½ÿ, Õ½ÿ, °Õ½ÿ} };

// Function definitions
