/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from tests/ctu/pass/func.ct
 */

// String literals
// Imported symbols

// Global forwarding

// Global initialization

// Function forwarding
signed int _Z5otherj(signed int arg0);
signed int main(signed int arg0);

// Function definitions
signed int _Z5otherj(signed int arg0) {
  signed int vreg0 = (signed int)20 * arg0;
  return vreg0;
  return;
}
signed int main(signed int arg0) {
  signed int (*o)(signed int);
  *&o = &_Z5otherj;
  signed int (*vreg1)(signed int) = *&o;
  signed int vreg2 = (*vreg1)(arg0);
  return vreg2;
  return;
}
