// generated by tests/pl0/prime.pl0
#include <stdbool.h>
typedef int type_integer;
typedef bool type_boolean;
typedef const char *type_string;
typedef void type_void;

extern type_integer printf(type_string, ...);

type_integer max[1];
type_integer arg[1];
type_integer ret[1];

type_void isprime(void);
type_void primes(void);
type_void main(void);

type_integer max[1] = { 100 };
type_integer arg[1] = { 0 };
type_integer ret[1] = { 0 };

type_void isprime(void) {
	type_integer i[1];
	*ret = 1;
	*i = 2;
	while (((i[0]) < (arg[0]))) {
		if (((((arg[0]) / (i[0])) * (i[0])) == (arg[0]))) {
			*ret = 0;
			*i = (arg[0]);
		}
		*i = ((i[0]) + 1);
	}
}

type_void primes(void) {
	*arg = 2;
	while (((arg[0]) < (max[0]))) {
		isprime();
		if (((ret[0]) == 1)) {
			printf("%d\n", (arg[0]));
		}
		*arg = ((arg[0]) + 1);
	}
}

type_void main(void) {
	primes();
}
