/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass::imports
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
signed int thing();
signed int thing();
signed int thing();

// Global initialization

// Function definitions
signed int thing() {
  signed int vreg0 = (*&thing)();
  return vreg0;
}
signed int thing() {
  signed int vreg0 = (*&thing)();
  return vreg0;
}
signed int thing() {
  signed int vreg0 = (*&thing)();
  return vreg0;
}
