/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::pl0
 */
#include <stddef.h>

// String literals
// Imported symbols
extern signed int printf(const char *arg0, ...);

// Global forwarding
signed long x;
signed long y;

// Function forwarding

// Global initialization
signed long x = (signed long)25;
signed long y = (signed long)625;

// Function definitions
