/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::pl0
 */
#include <stddef.h>

// String literals
// Imported symbols
extern signed int printf(const char *arg0, ...);

// Global forwarding
signed long a;
signed long b;

// Function forwarding

// Global initialization
signed long a = (signed long)25;
signed long b = (signed long)50;

// Function definitions
