/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::pl0
 */
#include <stddef.h>

// String literals
const char *strtab0 = "%d
";
// Imported symbols
extern signed int printf(const char *arg0, ...);

// Global forwarding
signed long x;
signed long squ;

// Function forwarding
void square();
void main();

// Global initialization
signed long x = (signed long)0;
signed long squ = (signed long)0;

// Function definitions
void square() {
  signed long vreg0 = *&x;
  signed long vreg1 = *&x;
  signed long vreg2 = vreg0 * vreg1;
  *&squ = vreg2;
  return;
}
void main() {
  *&x = (signed long)1;
block1: /* empty */;
  signed long vreg2 = *&x;
  _Bool vreg3 = vreg2 <= (signed long)10;
  if (vreg3) { goto block5; } else { goto block13; }
block5: /* empty */;
  (*&square)();
  signed long vreg7 = *&squ;
  signed int vreg8 = (*&printf)(strtab0, vreg7);
  signed long vreg9 = *&x;
  signed long vreg10 = vreg9 + (signed long)1;
  *&x = vreg10;
  goto block1;
block13: /* empty */;
  return;
}
