/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::pl0
 */
#include <stddef.h>

// String literals
// Imported symbols
extern signed int printf(const char *arg0, ...);

// Global forwarding
signed long a;
signed long b;
signed long c;
signed long x;
signed long y;
signed long z;

// Function forwarding

// Global initialization
signed long a = (signed long)0;
signed long b = (signed long)0;
signed long c = (signed long)0;
signed long x = (signed long)20;
signed long y = (signed long)50;
signed long z = (signed long)999;

// Function definitions
