#pragma once

#include "scan.h"

#include <stdbool.h>

/**
 * @defgroup LocationTracking AST location tracking
 * @brief AST source position tracking
 * @{
 */

/**
 * a position in a source file
 */
typedef unsigned node_t; // TODO: these should all take a context

const scan_t *get_node_scanner(node_t node);
where_t get_node_location(node_t node);

/**
 * @brief create a new node in a given file at a given location
 *
 * @param scan the scanner that this node is in
 * @param where the location of this node
 * @return the created node
 */
node_t node_new(const scan_t *scan, where_t where);

/**
 * @brief a sentinel node that is used to mark a location as being generated by
 * the compiler
 * @note this is a singleton and as such its safe to compare against it with
 * pointer equality
 *
 * @return the builtin node
 */
node_t node_builtin(void);

node_t node_invalid(void);

bool node_is_valid(node_t node);

/** @} */
