#pragma once

#include "scan.h"
#include "cthulhu/util/macros.h"

/* a position in a source file */
typedef struct {
    /* the scanner that this node is in */
    scan_t *scan;

    /* where in the source text this node is */
    where_t where;
} node_t;

/**
 * @brief create a new node in a given file at a given location
 * 
 * @param scan the scanner that this node is in
 * @param where the location of this node
 * @return the created node
 */
node_t *node_new(scan_t *scan, where_t where) NONULL;

/**
 * @brief a sentinel node that is used to mark a location as being generated by the compiler
 * @note this is a singleton and as such its safe to compare against it with pointer equality
 * 
 * @return the builtin node
 */
const node_t *node_builtin(void);
