/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass::funcs
 */
#include <stddef.h>

// String literals
// Imported symbols
extern void two();
extern void three();
extern void one();
extern void four();

// Global forwarding

// Function forwarding

// Global initialization

// Function definitions
