/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass::funcs
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
void two();
void three();
void one();
void four();

// Global initialization

// Function definitions
void two() {
  (*&three)();
  return;
}
void three() {
  (*&four)();
  return;
}
void one() {
  (*&two)();
  return;
}
void four() {
  (*&one)();
  return;
}
