/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
signed int main(signed int arg0, signed char** arg1);

// Global initialization

// Function definitions
signed int main(signed int arg0, signed char** arg1) {
  signed int argc2;
  signed int vreg0 = arg0 * (signed int)2;
  *&argc2 = vreg0;
  signed int vreg2 = *&argc2;
  return vreg2;
}
