/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
signed int main(signed int arg0, signed int arg1, _Bool arg2);

// Global initialization

// Function definitions
signed int main(signed int arg0, signed int arg1, _Bool arg2) {
  signed int;
  *&lambda1_4 = arg1;
  return;
}
