/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding
signed int x;
signed int y;
signed int z;

// Function forwarding

// Global initialization
signed int x = (signed int)25;
signed int y = (signed int)625;
signed int z = (signed int)625;

// Function definitions
