/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
const char *strtab0 = "Hello, World!";
// Imported symbols
extern signed int puts(const char *arg0);

// Global forwarding

// Function forwarding
signed int main();

// Global initialization

// Function definitions
signed int main() {
  signed int vreg0 = (*&puts)(strtab0);
  return vreg0;
}
