/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
void main();
void set(signed int* arg0);
void forward(signed int arg0);

// Global initialization

// Function definitions
void main() {
  (*&forward)((signed int)10);
  return;
}
void set(signed int* arg0) {
  signed int vreg0 = ???;
  *vreg0 = (signed int)25;
  return;
}
void forward(signed int arg0) {
  signed int* vreg0 = ???;
  (*&set)(vreg0);
  return;
}
