/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
signed int other(signed int arg0);
signed int main(signed int arg0);

// Global initialization

// Function definitions
signed int other(signed int arg0) {
  signed int vreg0 = (signed int)20 * arg0;
  return vreg0;
}
signed int main(signed int arg0) {
  signed int (*o)(signed int);
  *&o = &other;
  signed int (*vreg1)(signed int) = *&o;
  signed int vreg2 = (*vreg1)(arg0);
  return vreg2;
}
