/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
const char *strtab0 = "I\x03";
const char *strtab1 = "=\x03";
// Imported symbols

// Global forwarding
const char *DSx;
const char *Dcx;
const char *Dc;
const char *Dct;

// Function forwarding

// Global initialization
const char *DSx = "\x02";
const char *Dcx = "\x02";
const char *Dc = "\x02";
const char *Dct = "\x02";

// Function definitions
