/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
signed int fib(signed int arg0);
signed int main(signed int arg0, signed char** arg1);

// Global initialization

// Function definitions
signed int fib(signed int arg0) {
  _Bool vreg0 = arg0 < (signed int)2;
  if (vreg0) { goto block2; } else { goto block5; }
block2: /* empty */;
  return arg0;
block5: /* empty */;
  signed int vreg6 = arg0 - (signed int)1;
  signed int vreg7 = (*&fib)(vreg6);
  signed int vreg8 = arg0 - (signed int)2;
  signed int vreg9 = (*&fib)(vreg8);
  signed int vreg10 = vreg7 + vreg9;
  return vreg10;
}
signed int main(signed int arg0, signed char** arg1) {
  signed int vreg0 = (*&fib)((signed int)40);
  return vreg0;
}
