/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
void main();
signed int lambda2_12(signed int arg0);

// Global initialization

// Function definitions
void main() {
  signed int vreg0 = (*&lambda2_12)((signed int)5);
  return vreg0;
}
signed int lambda2_12(signed int arg0) {
  signed int vreg0 = arg0 * arg0;
  return vreg0;
}
