/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
void a();

// Global initialization

// Function definitions
void a() {
  signed int x;
  signed int z;
  *&x = (signed int)5;
  signed int vreg1 = *&x;
  *&z = vreg1;
  return;
}
