/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
const char *strtab0 = "lol";
// Imported symbols

// Global forwarding
const char *x;

// Function forwarding

// Global initialization
const char *x = "\x02";

// Function definitions
