/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
signed int take1(signed int* arg0);
signed int refarg(signed int arg0);
signed int take3(signed int*** arg0);
signed int take0(signed int arg0);

// Global initialization

// Function definitions
signed int take1(signed int* arg0) {
  signed int vreg0 = ???;
  return vreg0;
}
signed int refarg(signed int arg0) {
  signed int* vreg0 = ???;
  signed int vreg1 = (*&take1)(vreg0);
  return vreg1;
}
signed int take3(signed int*** arg0) {
  signed int** vreg0 = ???;
  signed int* vreg1 = ???;
  signed int vreg2 = ???;
  return vreg2;
}
signed int take0(signed int arg0) {
  return arg0;
}
