/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
const char *strtab0 = "entry";
const char *strtab1 = "custom init";
// Imported symbols
extern signed int puts(const char *arg0);

// Global forwarding
__attribute__((section(".init_array")))
void (*lambda4_7)();

// Function forwarding
void main();
void lambda4_18();

// Global initialization
void (*lambda4_7)() = lambda4_18;

// Function definitions
void main() {
  signed int vreg0 = (*&puts)(strtab0);
  return vreg0;
}
void lambda4_18() {
  signed int vreg0 = (*&puts)(strtab1);
  return vreg0;
}
