/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
signed int main();
signed int __fun(signed int arg0);

// Global initialization

// Function definitions
signed int main() {
  signed int vreg0 = (*&__fun)((signed int)25);
  return vreg0;
}
signed int __fun(signed int arg0) {
  signed int vreg0 = arg0 + arg0;
  return vreg0;
}
