/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
const char *strtab0 = "hello";
// Imported symbols

// Global forwarding

// Function forwarding
signed int main(signed int arg0, signed char** arg1);
const char *hello();

// Global initialization

// Function definitions
signed int main(signed int arg0, signed char** arg1) {
  const char *x;
  const char *vreg0 = (*&hello)();
  *&x = vreg0;
  return;
}
const char *hello() {
  return strtab0;
}
