/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from mnt::c::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass
 */
#include <stddef.h>

// String literals
// Imported symbols

// Global forwarding

// Function forwarding
signed int empty(_Bool arg0);

// Global initialization

// Function definitions
signed int empty(_Bool arg0) {
  signed int x14[1];
  *x14 = (signed int)10;
  if (arg0) { goto block2; } else { goto block7; }
block2: /* empty */;
  signed int vreg3 = *x14;
  signed int vreg4 = vreg3 * (signed int)100;
  *x14 = vreg4;
  goto block9;
block7: /* empty */;
  *x14 = (signed int)50;
block9: /* empty */;
  signed int vreg10 = *x14;
  return vreg10;
}
