/**
 * Autogenerated by the Cthulhu Compiler Collection C99 backend
 * Generated from C:::Users::ehb56::OneDrive::Documents::GitHub::ctulang::tests::ctu::pass::builtins
 */
#include <stddef.h>

// String literals
const char *strtab0 = "sizeof(char) = %d\n";
const char *strtab1 = "sizeof(short) = %d\n";
const char *strtab2 = "sizeof(int) = %d\n";
const char *strtab3 = "sizeof(long) = %d\n";
// Imported symbols
extern signed int printf(const char *arg0, ...);

// Global forwarding

// Function forwarding
signed int main();
size_t lambda5_33();
size_t lambda6_34();
size_t lambda7_32();
size_t lambda8_33();

// Global initialization

// Function definitions
signed int main() {
  size_t vreg0 = (*&lambda5_33)();
  signed int vreg1 = (*&printf)(strtab0, vreg0);
  size_t vreg2 = (*&lambda6_34)();
  signed int vreg3 = (*&printf)(strtab1, vreg2);
  size_t vreg4 = (*&lambda7_32)();
  signed int vreg5 = (*&printf)(strtab2, vreg4);
  size_t vreg6 = (*&lambda8_33)();
  signed int vreg7 = (*&printf)(strtab3, vreg6);
  return;
}
size_t lambda5_33() {
  size_t vreg0 = sizeof(signed char);
  return vreg0;
}
size_t lambda6_34() {
  size_t vreg0 = sizeof(signed short);
  return vreg0;
}
size_t lambda7_32() {
  size_t vreg0 = sizeof(signed int);
  return vreg0;
}
size_t lambda8_33() {
  size_t vreg0 = sizeof(signed long);
  return vreg0;
}
