
expr =  IDENT |
        literal |
        function_call |
        expr binop expr |
        unop expr |
        "(" expr ")" ;





type = [ "&" ] typebody ;

typebody = [ array | "*"* ] typebody | typename ;

array = "[" expr? "]" ;

typename = IDENT | IDENT "::" typename ;
