name: build and test compiler
on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'include/**'
      - 'driver/**'
      - 'plugins/**'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'include/**'
      - 'driver/**'
      - 'plugins/**'

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Run Test Suite
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          choco: winflexbison
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          meson-version: 0.58.0
