name: formatting checks
on:
  push:
    branches: [master]
    paths:
      - 'common/**'
      - 'cthulhu/**'
      - 'driver/**'
      - 'interface/**'
  pull_request:
    branches: [master]
    paths:
      - 'common/**'
      - 'cthulhu/**'
      - 'driver/**'
      - 'interface/**'

jobs:
  formatting-check:
    name: Formatting Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'common'
          - 'cthulhu'
          - 'driver'
          - 'interface'
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.5.0
        with:
          clang-format-version: '13'
          check-path: ${{ matrix.path }}
          fallback-style: Microsoft
