name: formatting checks
on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'include/**'
      - 'driver/**'
      - 'plugins/**'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'include/**'
      - 'driver/**'
      - 'plugins/**'

jobs:
  formatting-check:
    name: Formatting Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'include'
          - 'driver'
          - 'plugins'
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.5.0
        with:
          clang-format-version: '13'
          check-path: ${{ matrix.path }}
          fallback-style: Microsoft
