name: Build & Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config: 
          - { name: "windows-msvc", os: windows-latest, cc: "cl", cxx: "cl", options: "-Dcpp_std=c++latest" }
          - { name: "windows-clang", os: windows-latest, cc: "clang", cxx: "clang-cl", options: "-Dcpp_std=c++latest" }
          - { name: "linux-gcc", os: ubuntu-20.04, cc: "gcc", cxx: "g++", options: "-Dcpp_std=c++2a" }
          - { name: "linux-clang", os: ubuntu-20.04, cc: "clang", cxx: "clang++", options: "-Dcpp_std=c++2a" }
          - { name: "macos-clang", os: macos-latest, cc: "clang", cxx: "clang++", options: "-Dcpp_std=c++2a" }
          
    steps:
      - uses: ilammy/msvc-dev-cmd@v1.5.0
        if: ${{ matrix.config.os }} == 'windows-msvc'
      - uses: actions/checkout@master
        with:
          submodules: 'true'
      - uses: ashutoshvarma/setup-ninja@master
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.2
        with:
          action: test
          setup-options: ${{ matrix.config.options }}
          meson-version: 0.57.1
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
