name: Build & Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config: 
          - { name: "linux-gcc", os: ubuntu-20.04, cc: "gcc" }
          - { name: "linux-clang", os: ubuntu-20.04, cc: "clang" }
          
    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'true'
      - uses: ashutoshvarma/setup-ninja@master
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.2
        with:
          action: test
          meson-version: 0.59.0
        env:
          CC: ${{ matrix.config.cc }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ matrix.config.name }}
          path: ${{ github.workspace }}/build/
