name: Run Clang Format
on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'include/**'
      - 'driver/**'
      - 'plugins/**'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'include/**'
      - 'driver/**'
      - 'plugins/**'

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Run Test Suite
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          meson-version: 0.58.0
  formatting-check:
    name: Formatting Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'include'
          - 'driver'
          - 'plugins'
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.5.0
        with:
          clang-format-version: '13'
          check-path: ${{ matrix.path }}
          fallback-style: Microsoft
