name: publish docs
on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'include/**'
      - 'driver/**'

  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'include/**'
      - 'driver/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: doxygen graphviz
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: docs
          directory: build
          meson-version: 0.58.0
      - uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: docs/html
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
